## Installing Numpy

In [1]:
!pip install numpy ## Installing numpy

In [2]:
## Getting version of NUmpy
import numpy as np

In [3]:
print(np.__version__)

1.19.2


In [6]:
## Creating array
arr=np.array(1) ## Array with zero dimension i.e. point
arr

array(1)

In [1]:
import numpy as np


In [2]:
arr=np.array(1)

In [3]:
arr

array(1)

In [4]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
arr.ndim ## to check the dimendsion of array

1

In [6]:
arr.size ## To determine the array of size

4

In [7]:
arr.shape ## To determine the number of rows and columns

(4,)

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr.max()

4

In [10]:
arr.mean()

2.5

In [12]:
arr.var()

1.25

In [13]:
## Creating array with string vallue
arr=np.array(["ayush","varun","rahul"])

In [14]:
arr

array(['ayush', 'varun', 'rahul'], dtype='<U5')

In [15]:
arr.ndim

1

In [16]:
arr.shape

(3,)

In [17]:
arr.size

3

In [20]:
arr.dtype

dtype('<U5')

In [21]:
type(arr)

numpy.ndarray

## Creating 2-D array

In [26]:
 arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [24]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr.ndim

2

In [28]:
arr.shape

(3, 4)

In [29]:
arr.size

12

In [30]:
arr.dtype

dtype('int32')

In [31]:
type(arr)

numpy.ndarray

In [35]:
## Creating array with tupel
a=np.array(((1,2,3,4),(1,2,3,4))) ## 2-D array

In [36]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [37]:
a.ndim

2

In [1]:
import numpy as np

In [2]:
## Creating 3-D array

In [10]:
arr=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

In [4]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
arr.ndim

4

## Methods
* arrange
* linspace
* ravel
* random

In [12]:
np.arange(5) # stop

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1,5) #Start, stop

array([1, 2, 3, 4])

In [14]:
np.arange(1,10,2) # start, stop, step

array([1, 3, 5, 7, 9])

In [15]:
np.abs(a)

NameError: name 'a' is not defined

In [16]:
a=33.14


In [17]:
np.abs(a)

33.14

In [26]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [18]:
np.arange(50,100,5).reshape(2,5)
## reshape is used for getting no. element multiplied perfectlt

array([[50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [20]:
a=np.arange(50,100,5).reshape(5,2)

In [21]:
a

array([[50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [22]:
a.ndim

2

In [23]:
a.shape

(5, 2)

In [24]:
a.size

10

In [28]:
a=np.arange(50,100,5).reshape(5,2,1) ## Here dimension is getting higher

In [29]:
a

array([[[50],
        [55]],

       [[60],
        [65]],

       [[70],
        [75]],

       [[80],
        [85]],

       [[90],
        [95]]])

In [30]:
a.ndim

3

In [31]:
b=np.arange(50,100,5).reshape(1,1,1,2,5)

In [32]:
b

array([[[[[50, 55, 60, 65, 70],
          [75, 80, 85, 90, 95]]]]])

In [33]:
b.ndim

5

In [34]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
np.arange(1,21).reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [36]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
np.linspace(1,50,10) ## start stop and the no. of elemnt we need

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [38]:
np.linspace(1,50,20) ## @0 is no. of element we need

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [39]:
np.linspace(1,50,10,retstep='True') ## retstep ="True" will tell u the difference between element

(array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
        28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ]),
 5.444444444444445)

In [1]:
import numpy as np

In [5]:
## ravel- conert arry of any dim. to 1 dim
a=np.arange(5,51,5).reshape(2,5)
a.ravel()

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [8]:
a=np.arange(50).reshape(5,10)
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
## Creat 2 -d array and conver it in 1-D
a=np.arange(5,51,5).reshape(2,5)
a.ravel()

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

## Random function

In [14]:
np.random.rand(5)

array([0.58189936, 0.1489618 , 0.10684223, 0.11449065, 0.59944926])

In [19]:
np.random.rand(5)*100
# broadcasting mean individually mathematical operation
# all mathematical operation will work here

array([ 1.98419208, 25.71964507, 50.14915037, 59.11731038, 37.75927413])

In [21]:
print(np.random.rand(5)+100)
print(np.random.rand(5)*100)

[100.91704615 100.81917463 100.60495238 100.07859177 100.63834097]
[97.18892842 74.89509639 40.27273196 83.55194822 34.32991847]


In [23]:
## To get the integer data
np.random.randint(5)

3

In [24]:
np.random.randint(5)*100

200

In [25]:
np.random.randint(5)+100

103

In [28]:
np.random.rand(10).reshape(5,2)

array([[0.35767836, 0.51159792],
       [0.06257103, 0.74715358],
       [0.99931915, 0.10479445],
       [0.03149833, 0.43990525],
       [0.15572262, 0.84015757]])

In [34]:
a=np.linspace(1,50,5,retstep=True,dtype=str) ## using data type

In [35]:
a

(array(['1.0', '13.25', '25.5', '37.75', '50.0'], dtype='<U32'), 12.25)

In [36]:
a=np.linspace(0,50,11)

In [37]:
type(a)

numpy.ndarray

In [38]:
a

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [39]:
a=np.random.randint(1,10,2)

In [40]:
a

array([6, 5])

In [1]:
import numpy as np

In [3]:
np.random.rand(10)

array([0.07436845, 0.86780666, 0.51869576, 0.63136023, 0.5005751 ,
       0.74748224, 0.42425532, 0.81521702, 0.52661604, 0.31950681])

In [4]:
np.random.rand(10)+100

array([100.94826268, 100.46379373, 100.68099621, 100.0966218 ,
       100.78073739, 100.24706034, 100.91818292, 100.34793973,
       100.18302452, 100.37030445])

In [5]:
np.random.randint(1,50,5) ## start ,stop,mo.of element we want

array([37, 21,  4, 10, 35])

In [6]:
np.random.randint(3,size=10)

array([0, 0, 1, 2, 1, 2, 1, 2, 1, 2])

## Numpy Array Indexing

In [10]:
## indexing in 1d
arr=np.array([1,2,3,4,5,6,7])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
arr[0]

1

In [13]:
arr[1:4]

array([2, 3, 4])

In [14]:
 arr=np.array([[1,2,3,4],[5,6,7,8]])## Silicing in 2-D

In [15]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr[0,2]

3

In [17]:
arr[1,3]

8

In [1]:
import numpy as np

In [2]:
arr=np.array([[[1,2,3,4],[5,6,7,8],[10,11,12,13]]])

In [8]:
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]]])

In [11]:
arr.ndim

3

In [12]:
arr[0,1]

array([5, 6, 7, 8])

In [16]:
arr[0,2,2]

12

## Numpy Slicing

In [18]:
arr=np.array([1,2,3,4,5,6])

In [19]:
arr

array([1, 2, 3, 4, 5, 6])

In [20]:
arr[1:2]## Silicing in 1-D

array([2])

In [21]:
arr[1:5]

array([2, 3, 4, 5])

In [22]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [23]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
arr.ndim

2

In [25]:
## silicing in 2-D
arr[0,1:3]

array([2, 3])

In [26]:
arr[1,2:4]

array([8, 9])

## Broadcasting

In [29]:
a1=np.arange(24).reshape(4,6)
a1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
a2=np.arange(24).reshape(6,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
a2*10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150],
       [160, 170, 180, 190],
       [200, 210, 220, 230]])

In [32]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
a2+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

In [34]:
## Changing the value in element
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
a2[0:2]=10 # Changing the data 
a2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
a2[4:,1:3]= 20

In [44]:
a2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 20, 20, 20],
       [20, 20, 20, 23]])

## Zero's and One's

In [46]:
## Creating array with zeros
np.zeros(2) ## 1-D array with 2 element and each element is zero

array([0., 0.])

In [53]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
## Creating array with ones
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
a=np.ones((2,3),dtype=int)

In [58]:
a.ndim

2

In [59]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [61]:
## Array with daignol element
np.eye((3),dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
a=np.arange(24).reshape(4,6)

In [64]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [65]:
np.max(a) ## getting maximun 

23

In [66]:
np.min(a)

0

In [67]:
np.sum(a)

276

In [68]:
np.mean(a)

11.5

In [69]:
np.median(a)

11.5

## Stacking
* Stacking is used to join a sequence of same dimension arrays along a new axis

In [71]:
import numpy as np

In [73]:
arr1=np.array([1,2,3,4])

In [74]:
arr2=np.array([5,6,7,8])

In [76]:
arr=np.stack((arr1,arr2))## Horizental stack axis=0

In [77]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
arr3=np.stack((arr1,arr2),axis=1) ## vertically stacking
arr3

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [83]:
a1=np.arange(10,50).reshape(10,4)

In [84]:
a1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45],
       [46, 47, 48, 49]])

In [85]:
a2=np.linspace(10,50,40).reshape(10,4)
a2

array([[10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.64102564, 36.66666667, 37.69230769],
       [38.71794872, 39.74358974, 40.76923077, 41.79487179],
       [42.82051282, 43.84615385, 44.87179487, 45.8974359 ],
       [46.92307692, 47.94871795, 48.97435897, 50.        ]])

In [86]:
np.hstack((a1,a2)) ## stacking arrays column wise

array([[10.        , 11.        , 12.        , 13.        , 10.        ,
        11.02564103, 12.05128205, 13.07692308],
       [14.        , 15.        , 16.        , 17.        , 14.1025641 ,
        15.12820513, 16.15384615, 17.17948718],
       [18.        , 19.        , 20.        , 21.        , 18.20512821,
        19.23076923, 20.25641026, 21.28205128],
       [22.        , 23.        , 24.        , 25.        , 22.30769231,
        23.33333333, 24.35897436, 25.38461538],
       [26.        , 27.        , 28.        , 29.        , 26.41025641,
        27.43589744, 28.46153846, 29.48717949],
       [30.        , 31.        , 32.        , 33.        , 30.51282051,
        31.53846154, 32.56410256, 33.58974359],
       [34.        , 35.        , 36.        , 37.        , 34.61538462,
        35.64102564, 36.66666667, 37.69230769],
       [38.        , 39.        , 40.        , 41.        , 38.71794872,
        39.74358974, 40.76923077, 41.79487179],
       [42.        , 43.        

In [87]:
## Vstacking
np.vstack((a1,a2))  ## row wise stacked

array([[10.        , 11.        , 12.        , 13.        ],
       [14.        , 15.        , 16.        , 17.        ],
       [18.        , 19.        , 20.        , 21.        ],
       [22.        , 23.        , 24.        , 25.        ],
       [26.        , 27.        , 28.        , 29.        ],
       [30.        , 31.        , 32.        , 33.        ],
       [34.        , 35.        , 36.        , 37.        ],
       [38.        , 39.        , 40.        , 41.        ],
       [42.        , 43.        , 44.        , 45.        ],
       [46.        , 47.        , 48.        , 49.        ],
       [10.        , 11.02564103, 12.05128205, 13.07692308],
       [14.1025641 , 15.12820513, 16.15384615, 17.17948718],
       [18.20512821, 19.23076923, 20.25641026, 21.28205128],
       [22.30769231, 23.33333333, 24.35897436, 25.38461538],
       [26.41025641, 27.43589744, 28.46153846, 29.48717949],
       [30.51282051, 31.53846154, 32.56410256, 33.58974359],
       [34.61538462, 35.

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2=np.array([4,5,6])

In [6]:
arr3=np.stack((arr1,arr2),axis=1)

In [7]:
arr3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
## Spliting
## split an array into multiple sub-arrays as views into array
ab1=np.arange(15).reshape(5,3)
ab2=np.arange(20,35).reshape(5,3)

In [12]:
np.hsplit(ab1,3) ## 3 represent the no. of column we have 

[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])]

In [14]:
np.vsplit(ab1,5) ## 5 represent the number of rows here.

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14]])]

In [15]:
 ## Boolean Masking
ab1=np.arange(15).reshape(5,3)

In [16]:
ab1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
re=0==ab1%2 ## re= what output we want== Condition

In [18]:
re

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [19]:
ab1[re] ## taking element whic is making condition true and making it in 1-D array

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [34]:
 ## Copy Operation
## Used as a backup

In [20]:
arr=np.array([1,2,3,4])

In [24]:
arr[2:]=300

In [25]:
arr

array([  1,   2, 300, 300])

In [26]:
arr1=arr.copy() ## Creating copy function

In [27]:
arr1

array([  1,   2, 300, 300])

In [29]:
arr[3]=50

In [30]:
arr

array([  1,   2, 300,  50])

In [31]:
arr1

array([  1,   2, 300, 300])

In [32]:
arr[1:3]=[4,5]## Changing multiple data 

In [33]:
arr

array([ 1,  4,  5, 50])

In [35]:
## Arranging arrays
arr=np.array([1,55,35,44,66,45,23,43,55,78,76,88,56,887,54])

In [48]:
np.sort(arr)

array([  1,  23,  35,  43,  44,  45,  54,  55,  55,  56,  66,  76,  78,
        88, 887])

In [53]:
arr

array([  1,  23,  35,  43,  44,  45,  54,  55,  55,  56,  66,  76,  78,
        88, 887])

In [1]:
import numpy as np

In [2]:
## Filter Condition
a=np.array([[1,2,3,4],[5,6,4,8],[9,2,11,12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  4,  8],
       [ 9,  2, 11, 12]])

In [4]:
a[a<5]# filter condition is applied

array([1, 2, 3, 4, 4, 2])

In [6]:
np.sort(a)

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  8],
       [ 2,  9, 11, 12]])

In [7]:
a.sort()

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  8],
       [ 2,  9, 11, 12]])

In [12]:
## Search operation 
arr=np.array([1,2,3,4,4,5,6,7])
np.where(arr==1)

(array([0], dtype=int64),)

In [15]:
## Universal Function
print("THe valu of PI is",np.pi)
print("The value of sqrt is",np.sqrt(25))

THe valu of PI is 3.141592653589793
The value of sqrt is 5.0


In [17]:
np.sin(90)

0.8939966636005579

In [18]:
## Converting degrre into radins
d=np.arange(0,120,30).reshape(2,2)

In [19]:
d

array([[ 0, 30],
       [60, 90]])

In [20]:
d_rad=d*np.pi/180  ## Converting degree into radian.

In [21]:
d_rad

array([[0.        , 0.52359878],
       [1.04719755, 1.57079633]])